language: java

jdk:
  - openjdk6
  - oraclejdk7

branches:
  only:
  - develop

notifications:
  webhooks: https://hook.bearychat.com/=bw63g/travis/7c386582687b61b7e86b12d59b2655b2
  email:
  - xxliu@ilegendsoft.com
  - yyang@ilegendsoft.com

