language: java

jdk:
  - openjdk6
  - oraclejdk7

branches:
  only:
  - develop

notifications:
  slack: ilegendsoft:Ub9XZ7ohD1Eg5sdVgGLpSYjM
  email:
  - xxliu@ilegendsoft.com
  - yyang@ilegendsoft.com

